name: Prepare GitHub Release

on:
  push:
    tags:
      - '*'

jobs:
  attach-zip:
    name: Prepare GitHub Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      -
        name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          tools: composer:v2.2
          coverage: none
      -
        name: Checkout
        uses: actions/checkout@v6
      -
        name: Create draft release
        uses: concrete5-community/gh-package-release-attach@main
        with:
          remove-files: |
            composer.json
          publish-release: true
